import { useState } from "react";
import { useToast } from "./Toast";

const tabs = [
  "Commit",
  "Description",
  "PR Title",
  "PR Description",
  "Branch",
  "Risk",
  "Type",
  "Scope",
  "Changelog",
  "Release Notes",
];

export default function OutputTabs({ result }) {
  const [activeTab, setActiveTab] = useState("Commit");
  const [copiedTab, setCopiedTab] = useState(null);

  const addToast = useToast();

  const getContent = () => {
    switch (activeTab) {
      case "Commit":
        return result.commit;

      case "Description":
        return result.description;

      case "PR Title":
        return result.prTitle;

      case "PR Description":
        return result.prDescription;

      case "Branch":
        return result.branchName;

      case "Risk":
        return result.riskLevel;

      case "Type":
        return result.type;

      case "Scope":
        return result.scope;

      case "Changelog":
        return result.changelog;

      case "Release Notes":
        return result.releaseNotes;

      default:
        return "";
    }
  };

  const content = getContent();

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content || "");

      setCopiedTab(activeTab);

      addToast(`${activeTab} copied`);

      setTimeout(() => {
        setCopiedTab(null);
      }, 2000);

    } catch (err) {
      console.error(err);
      addToast("Copy failed");
    }
  };

  return (
    <div className="max-w-6xl mx-auto mt-10 px-4">

      <div className="flex flex-wrap gap-3 mb-6">
        {tabs.map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`px-4 py-2 rounded-lg transition ${
              activeTab === tab
                ? "bg-cyan-500 text-white"
                : "bg-slate-800 text-gray-300 hover:bg-slate-700"
            }`}
          >
            {tab}
          </button>
        ))}
      </div>

      <div className="bg-slate-800 rounded-xl border border-slate-700 shadow-xl p-6 min-h-[320px]">

        <div className="flex justify-between items-center mb-5">

          <h2 className="text-xl font-bold">
            {activeTab}
          </h2>

          {content && (
            <button
              onClick={handleCopy}
              className="px-4 py-2 rounded-lg bg-cyan-500 hover:bg-cyan-600"
            >
              {copiedTab === activeTab ? "✅ Copied" : "📋 Copy"}
            </button>
          )}

        </div>

        {content ? (
          <pre className="whitespace-pre-wrap text-gray-300 leading-7">
            {content}
          </pre>
        ) : (
          <div className="flex flex-col justify-center items-center h-64">

            <div className="text-6xl mb-5">
              🤖
            </div>

            <h2 className="text-2xl font-bold">
              Ready to Generate
            </h2>

            <p className="mt-4 text-gray-400 text-center max-w-lg">
              Paste your Git diff and click
              <span className="text-cyan-400 font-semibold">
                {" "}Generate
              </span>
              .
            </p>

          </div>
        )}

      </div>

      {result.provider && (
        <div className="mt-5 text-right text-gray-400 text-sm">
          Generated by <span className="text-cyan-400">{result.provider}</span>
        </div>
      )}
    </div>
  );
}